val root = project.in(file("."))
  .configs(IntegrationTest)
  .settings(name := "accounts-api")
  .settings(mainClass in assembly := Some("accounts.application.Main"))
  .settings(Settings.withCommonSettings: _*)
  .settings(Settings.withAssembly: _*)
  .settings(Settings.withTesting: _*)
  .settings(Defaults.itSettings:_*)
  .settings(Settings.withBuildInfo: _*)
  .settings(Settings.withDockerSetting: _*)
  .settings(inThisBuild(libraryDependencies ++= Settings.logging ++ Settings.http ++ Settings.database ++ Settings.configs ++ Settings.testing))
  .enablePlugins(BuildInfoPlugin, AssemblyPlugin, DockerPlugin)
