version: '3.3'

services:
  api:
    image: accounts/accounts-api:latest
    volumes:
    - ./config:/config
    ports:
    - 4140:80
    environment:
      HTTP_INTERFACE: "0.0.0.0"
      HTTP_PORT: 80
      _JAVA_OPTIONS: "-Dlogback.configurationFile=/config/logback.xml"
    restart: always
